### ISSUE TITLE
How to install packages using Firely Terminal for a Fhir server with access token

### ISSUE THREAD

**Issue by pvnmurthy** [FirelyTeam/firely-docs-firely-terminal#1]
Hi,

Please let me know how I can install a package to a fhir server protected by an access token.

These are the steps that I followed:
>fhir server add localfhir http://localhost:8081/hapi-fhir-jpaserver/fhir --default
>fhir install hl7.fhir.us.carin-bb 1.0.0
>fhir install hl7.fhir.us.davinci-pdex-plan-net 1.0.0

Please help. Appreciate your help.
Thank you in advance.

**Comment by wardweistra** [comment]
Hi @pvnmurthy,

`fhir install` will install the package to your local working directory, not a connected server.
Please find in the manual of your FHIR server how to load the conformance resources from a package to that server or ask for help at https://chat.fhir.org/#narrow/stream/179167-hapi.

Best regards,
Ward
