### ISSUE TITLE
Authenticating to a remote FHIR server

### ISSUE THREAD

**Issue by SharonHart** [FirelyTeam/firely-docs-firely-terminal#25]
Hi, to upload conformance resources in a fhir package, how do I authenticate to a remote server that I've added to the terminal tool before POSTing?

**Comment by wardweistra** [comment]
Hi @SharonHart, with `fhir server header` you can add extra HTTP headers that will be used when communicating with the server you've configured.

So generally:
* Authenticate to the FHIR server, for example with Postman, to get an access token
* Add the server to Firely Terminal with `fhir server add`
* Add the Authorization header to that server with `fhir server header`

Please reach out to simplifier@fire.ly if you have any more questions!

**Comment by mharthoorn** [comment]
If the server uses _basic_ authentication, you can also use `fhir server authorize basic user=... password=...`
This will create the proper headers for you.

We are willing to expand this to other types of authorization, if it is sufficiently standardized and broadly supported.

**Comment by SharonHart** [comment]
Thanks! Header should do the trick, havent seen this command
